# Generated by Django 4.1 on 2022-08-17 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LsApp', '0007_remove_post_like_users_post_likes_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': False},
        ),
    ]
