
# Generated by Django 4.0.4 on 2022-08-19 11:08


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LsApp', '0010_remove_post_likes_post_like_count_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.PositiveIntegerField(null=True, verbose_name='오늘 올라온 실수들')),
            ],
        ),
    ]
